social_auth_linkedin.settings:
  type: config_object
  label: 'Social Auth Linkedin settings'
  mapping:
    app_id:
      type: string
      label: 'Application ID'
    app_secret:
      type: string
      label: 'App Secret'
    graph_version:
      type: float
      label: 'Linkedin Graph API version'
